v1=input('Digite algo: ')
print('O tipo primitivo do valor é: ' , type(v1))
print('é numérico?',v1.isnumeric())
print('é alfabético?',v1.isalpha())
print('é alfanumérico?',v1.isalnum())
print('é decimal?',v1.isdecimal())
print('são apenas espaços?',v1.isspace())
print('são apenas maiusculas?',v1.isupper())
print('são apenas minusculas',v1.islower())
print('está capitalizado?',v1.istitle())
print('pertence a tabela ASCII?',v1.isascii())