#faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada
v1=int(input('Introduz um número à tua escolha para ver a tabuada: '))
print('A tabuada de {} é :'.format(v1))
print('_' * 12)
print('1 x {:2} = {}'.format(v1,v1*1))
print('2 x {:2} = {}'.format(v1,v1*2))
print('3 x {:2} = {}'.format(v1,v1*3))
print('4 x {:2} = {}'.format(v1,v1*4))
print('5 x {:2} = {}'.format(v1,v1*5))
print('6 x {:2} = {}'.format(v1,v1*6))
print('7 x {:2} = {}'.format(v1,v1*7))
print('8 x {:2} = {}'.format(v1,v1*8))
print('9 x {:2} = {}'.format(v1,v1*9))
print('10 x {} = {}'.format(v1,v1*10))
print('_' * 12)